services:
  mysql:
    image: mysql:8.0.21
    container_name: mysql1
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: restSpringTCC
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  api1:
    build: .
    container_name: api1
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:      
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/restSpringTCC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_JPA_OPEN_IN_VIEW: "false"

volumes:
  mysql_data: