services:
  mysql:
    image: mysql:8.0.21
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: restSpringTCC
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  api1:
    build: .
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      hazelcast:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/restSpringTCC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_JPA_OPEN_IN_VIEW: "false"
  hazelcast:
    image: hazelcast/hazelcast:5.4.0
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5701/hazelcast/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
  management-center:
    image: hazelcast/management-center:5.8.0
    ports: [ 8081:8080 ]
    environment:
      MC_DEFAULT_CLUSTER: dev
      MC_DEFAULT_CLUSTER_MEMBERS: hazelcast

volumes:
  mysql_data: